package com.example.animeapp.theme

import androidx.compose.ui.graphics.Color

// Dark Colors
val DarkPrimary = Color(0xFFBDBDBD)
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkPrimaryContainer = Color(0xFF757575)
val DarkOnPrimaryContainer = Color(0xFFFFFFFF)
val DarkSecondary = Color(0xFFBDBDBD)
val DarkOnSecondary = Color(0xFFFFFFFF)
val DarkSecondaryContainer = Color(0xFF757575)
val DarkOnSecondaryContainer = Color(0xFFFFFFFF)
val DarkTertiary = Color(0xFFBDBDBD)
val DarkOnTertiary = Color(0xFFFFFFFF)
val DarkTertiaryContainer = Color(0xFF757575)
val DarkOnTertiaryContainer = Color(0xFFFFFFFF)
val DarkError = Color(0xFFB00020)
val DarkOnError = Color(0xFFFFFFFF)
val DarkErrorContainer = Color(0xFFCF6679)
val DarkOnErrorContainer = Color(0xFF1B1B1F)
val DarkBackground = Color(0xFF121212)
val DarkOnBackground = Color(0xFFE0E0E0)
val DarkSurface = Color(0xFF212121)
val DarkOnSurface = Color(0xFFE0E0E0)
val DarkSurfaceVariant = Color(0xFF37474F)
val DarkOnSurfaceVariant = Color(0xFFE0E0E0)
val DarkOutline = Color(0xFF546E7A)
val DarkInverseSurface = Color(0xFFE3E2E6)
val DarkInverseOnSurface = Color(0xFF000000)
val DarkInversePrimary = Color(0xFF1D3557)
val DarkSurfaceTint = Color(0xFF1D3557)
val DarkOutlineVariant = Color(0xFF37474F)
val DarkScrim = Color(0xFF000000)